CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    role ENUM('FARMER','TRANSPORT_PROVIDER','ADMIN') NOT NULL,

    full_name VARCHAR(100) NOT NULL,

    mobile_number VARCHAR(10) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    state VARCHAR(100) NOT NULL,

    district VARCHAR(100) NOT NULL,

    taluka VARCHAR(100) NOT NULL,

    village VARCHAR(100) NOT NULL,

    is_mobile_verified BOOLEAN DEFAULT FALSE,

    account_status ENUM('ACTIVE','INACTIVE','BLOCKED') DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);